from django.urls import path
from . import views


urlpatterns = [
    path('',views.login_view,name="login"),
    path('signup/',views.signup,name="signup"),
    path('home/',views.Home,name="home"),
    path("profile/", views.profile_redirect, name="profile"),
    path('artistview/',views.artistview,name="artist-view"),
    path("event_register/", views.event_management_register,name="event_register"),
    path('eventview/',views.eventview,name="event-view"),
    path('eventhome/',views.eventview,name="event-home"),
    path("logout/", views.user_logout, name="logout"),
    path('packages/', views.event_packages_view, name='event-packages'),
    path('package/<int:id>/', views.package_detail, name='package-detail'),
    path("artist-register/", views.artist_register, name="artist-register"),
    path("admin-dashboard/",views.admin_dashboard,name="admin-dashboard"),
    path("user-payments/",views.user_payments,name="user-payments"),
    path("admin-artists/",views.admin_artists,name="admin-artists"),
    path("approve-artist/<int:id>/",views.approve_artist,name="approve-artist"),   
    path("reject-artist/<int:id>/",views.reject_artist,name="reject-artist"),
    path("admin-events/",views.admin_events,name="admin-events"),
    path("artist-history/",views.artist_booking_history,name="artist-history"),
    path("admin-revenue/",views.admin_revenue,name="admin-revenue"),
    path("admin-settings/",views.admin_settings,name="admin-settings"),
    path("approve-event/<int:id>/", views.approve_event, name="approve_event"),
    path("reject-event/<int:id>/", views.reject_event, name="reject_event"),
    path("event-details/<int:id>/", views.event_details, name="event_details"),
    path("artist-dashboard/",views.artist_dashboard,name="artist_dashboard"),
    path("artist-profile/",views.artist_profile,name="artist_profile"),
    path("artist-bookings-users/",views.artist_bookings,name="artist_bookings_users"),
    path("accept-booking/<int:id>/",views.accept_booking,name="accept_booking"),
    path("reject-booking/<int:id>/",views.reject_booking,name="reject_booking"),
    path("artist-payments/",views.artist_payments,name="artist_payments"),
    path("upload-portfolio/",views.upload_portfolio,name="upload_portfolio"),
    path("delete-portfolio/<int:id>/",views.event_portfolio,name="delete_portfolio"),
    path("user-dashboard/",views.user_dashboard,name="user-dashboard"),
    path("user-booking-history/", views.user_booking_history, name="user-booking-history"),
    path("event-dashboard/",views.event_dashboard,name="event_dashboard"),
    path("event-profile/",views.event_profile,name="event_profile"),
    path("user-profile/",views.user_profile,name="user-profile"),
    path("event-portfolio/",views.event_portfolio,name="event_portfolio"),
    path("delete-event-portfolio/<int:id>/",views.event_portfolio,name="delete_event_portfolio"),
    path("manage-events/",views.manage_events,name="manage_events"),
    path("add-event/",views.add_event,name="add_event"),
    path("delete-event/<int:id>/",views.delete_event,name="delete_event"),
    path("booking-requests/",views.booking_requests,name="booking_requests"),
    path("approve-booking/<int:id>/",views.approve_booking,name="approve_booking"),
    path("reject-booking/<int:id>/",views.reject_booking,name="reject_booking"),
    path("event-history/",views.event_booking_history,name="event-history"),
    path("my-bookings/",views.my_bookings,name="my_bookings"),
    path("event-payments/",views.event_payments,name="event_payments"),
    path('admin-event-details/<int:id>/', views.admin_event_details, name='admin-event-details'),
    path('artist-details/<int:id>/', views.admin_artist_details, name='artist-details'),
    path("artist_by_type/<str:type>/", views.artist_by_type, name="artist_by_type"),
    path("user-artist-detail/<int:id>/", views.user_artist_detail, name="user-artist-detail"),
    path("book-artist/<int:id>/", views.book_artist, name="book-artist"),
]

