# Generated by Django 6.0.3 on 2026-03-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventartist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpackage',
            name='package_type',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], default='Silver', max_length=10),
        ),
    ]
