# Generated by Django 6.0.3 on 2026-03-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventartist', '0002_eventpackage_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpackage',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventartist.eventtype'),
        ),
    ]
