# Generated by Django 6.0.3 on 2026-03-11 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventartist', '0003_eventpackage_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('stage_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('artist_type', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('previous_events', models.PositiveIntegerField()),
                ('skills', models.TextField()),
                ('price_start', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_end', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_city', models.CharField(max_length=200)),
                ('available_days', models.CharField(max_length=50)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(upload_to='artists/profile/')),
                ('social_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventartist.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artists/portfolio/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='eventartist.artist')),
            ],
        ),
    ]
