# Generated by Django 6.0.3 on 2026-03-11 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventartist', '0004_artist_artistportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventartist.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventartist.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventartist.eventmanagement')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventartist.eventtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventartist.useraccount')),
            ],
        ),
    ]
