# Generated by Django 6.0.3 on 2026-03-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventartist', '0005_artistbooking_eventbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='eventmanagement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
