# Generated by Django 6.0.3 on 2026-03-12 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventartist', '0006_artist_status_eventmanagement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpackage',
            name='services',
        ),
        migrations.AddField(
            model_name='artist',
            name='location',
            field=models.CharField(default='location', max_length=200),
        ),
        migrations.AddField(
            model_name='artistbooking',
            name='customer_phone',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='artistbooking',
            name='location',
            field=models.CharField(default='location', max_length=200),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='customer_phone',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='location',
            field=models.CharField(default='location', max_length=200),
        ),
        migrations.AlterField(
            model_name='artistbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventartist.artist')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventartist.artistbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventartist.useraccount')),
            ],
        ),
    ]
