# Generated by Django 6.0.3 on 2026-03-12 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventartist', '0007_remove_eventpackage_services_artist_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('silver_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platinum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_events', to='eventartist.eventmanagement')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventartist.eventtype')),
            ],
        ),
    ]
