# Generated by Django 6.0.3 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventartist", "0008_companyevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
